In [1]:
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
from numpy.random import randint as npRandint
from theano import function
import theano

In [2]:
theanoGenerator = RandomStreams(seed=npRandint(1, 1000))

In [3]:
from theano import config as Tconfig
theanoFloat  = Tconfig.floatX


In [16]:
probabilidad = theano.tensor.fscalar()
forma = (3,)

In [17]:
salida = theanoGenerator.binomial(size=forma, n=1, p=probabilidad, dtype=theanoFloat)

In [18]:
muestra = function(inputs=[probabilidad], outputs=salida)

In [19]:
muestra(0.3)

array([ 0.,  1.,  0.], dtype=float32)

In [20]:
matriz = theano.tensor.imatrix()

In [21]:
m = salida*matriz
mul = function(inputs=[probabilidad, matriz], outputs=[m,salida])

In [25]:
import numpy as np

ma=npRandint(low=0, high=10, size=(10,3), dtype=np.int32)


In [26]:
s1,s2=mul(0.5, ma)

In [28]:
s2

array([ 0.,  0.,  1.], dtype=float32)

In [30]:
ma

array([[0, 3, 0],
       [2, 7, 2],
       [3, 9, 2],
       [8, 5, 8],
       [4, 2, 5],
       [2, 0, 0],
       [0, 0, 9],
       [1, 1, 0],
       [2, 1, 8],
       [9, 5, 3]], dtype=int32)